port: 5000

mongodb:
  #modify your uri here: 
  # uri: mongodb+srv://Yomiel:Yomiel@mernauth.oz6dpip.mongodb.net/MERNauth?
  uri: mongodb+srv://rppen:1234567rppen@atlascluster.xktl2yd.mongodb.net/?retryWrites=true&w=majority
  retryWrites: true
  w: majority

jwt_secret: 123secret