port: 12345

mongodb:
  #modify your uri here: 
  # uri: mongodb+srv://Yomiel:Yomiel@mernauth.oz6dpip.mongodb.net/MERNauth?
  uri: mongodb+srv://weidaf:nLtEZHcLEjtZrA0A@cluster0.c1418is.mongodb.net
  retryWrites: true
  w: majority

jwt_secret: 123secret